export type StockStatus = 'Ready' | 'Low' | 'Backorder'

export type ProductKind =
  'backpack' | 'headphones' | 'bottle' | 'watch' | 'jacket' | 'camera'

export type Product = {
  id: string
  name: string
  kind: ProductKind
  sku: string
  stock: number
  status: StockStatus
  reserved: number
  incoming: number
  updatedAt: string
  variants?: Product[]
}

export const products: Product[] = [
  {
    id: 'fleet-backpack',
    name: 'Fleet Backpack 28L',
    kind: 'backpack',
    sku: 'BP-FLT-28',
    stock: 11982,
    status: 'Ready',
    reserved: 653,
    incoming: 2400,
    updatedAt: '2026-09-14',
    variants: [
      {
        id: 'fleet-backpack-black',
        name: 'Black',
        kind: 'backpack',
        sku: 'BP-FLT-28-BLK',
        stock: 6420,
        status: 'Ready',
        reserved: 301,
        incoming: 1200,
        updatedAt: '2026-09-14',
      },
      {
        id: 'fleet-backpack-sand',
        name: 'Sand',
        kind: 'backpack',
        sku: 'BP-FLT-28-SND',
        stock: 3890,
        status: 'Ready',
        reserved: 212,
        incoming: 800,
        updatedAt: '2026-09-13',
      },
      {
        id: 'fleet-backpack-olive',
        name: 'Olive',
        kind: 'backpack',
        sku: 'BP-FLT-28-OLV',
        stock: 1672,
        status: 'Low',
        reserved: 140,
        incoming: 400,
        updatedAt: '2026-09-12',
      },
    ],
  },
  {
    id: 'studio-headphones',
    name: 'Studio Headphones Pro',
    kind: 'headphones',
    sku: 'HP-STD-PRO',
    stock: 2104,
    status: 'Low',
    reserved: 388,
    incoming: 1500,
    updatedAt: '2026-09-15',
    variants: [
      {
        id: 'studio-headphones-graphite',
        name: 'Graphite',
        kind: 'headphones',
        sku: 'HP-STD-PRO-GRA',
        stock: 1240,
        status: 'Low',
        reserved: 240,
        incoming: 900,
        updatedAt: '2026-09-15',
      },
      {
        id: 'studio-headphones-silver',
        name: 'Silver',
        kind: 'headphones',
        sku: 'HP-STD-PRO-SIL',
        stock: 864,
        status: 'Low',
        reserved: 148,
        incoming: 600,
        updatedAt: '2026-09-15',
      },
    ],
  },
  {
    id: 'trail-bottle',
    name: 'Trail Insulated Bottle',
    kind: 'bottle',
    sku: 'BT-TRL-750',
    stock: 8430,
    status: 'Ready',
    reserved: 912,
    incoming: 0,
    updatedAt: '2026-09-11',
  },
  {
    id: 'orbit-watch',
    name: 'Orbit Smart Watch',
    kind: 'watch',
    sku: 'WT-ORB-S3',
    stock: 0,
    status: 'Backorder',
    reserved: 0,
    incoming: 3200,
    updatedAt: '2026-09-16',
    variants: [
      {
        id: 'orbit-watch-40',
        name: '40 mm',
        kind: 'watch',
        sku: 'WT-ORB-S3-40',
        stock: 0,
        status: 'Backorder',
        reserved: 0,
        incoming: 1800,
        updatedAt: '2026-09-16',
      },
      {
        id: 'orbit-watch-44',
        name: '44 mm',
        kind: 'watch',
        sku: 'WT-ORB-S3-44',
        stock: 0,
        status: 'Backorder',
        reserved: 0,
        incoming: 1400,
        updatedAt: '2026-09-16',
      },
      {
        id: 'orbit-watch-44-lte',
        name: '44 mm LTE',
        kind: 'watch',
        sku: 'WT-ORB-S3-44L',
        stock: 0,
        status: 'Backorder',
        reserved: 0,
        incoming: 0,
        updatedAt: '2026-09-10',
      },
      {
        id: 'orbit-watch-pro',
        name: 'Pro',
        kind: 'watch',
        sku: 'WT-ORB-S3-PRO',
        stock: 0,
        status: 'Backorder',
        reserved: 0,
        incoming: 0,
        updatedAt: '2026-09-09',
      },
    ],
  },
  {
    id: 'summit-jacket',
    name: 'Summit Shell Jacket',
    kind: 'jacket',
    sku: 'JK-SMT-SH',
    stock: 3275,
    status: 'Ready',
    reserved: 204,
    incoming: 600,
    updatedAt: '2026-09-13',
    variants: [
      {
        id: 'summit-jacket-m',
        name: 'M',
        kind: 'jacket',
        sku: 'JK-SMT-SH-M',
        stock: 1410,
        status: 'Ready',
        reserved: 96,
        incoming: 300,
        updatedAt: '2026-09-13',
      },
      {
        id: 'summit-jacket-l',
        name: 'L',
        kind: 'jacket',
        sku: 'JK-SMT-SH-L',
        stock: 1865,
        status: 'Ready',
        reserved: 108,
        incoming: 300,
        updatedAt: '2026-09-13',
      },
    ],
  },
  {
    id: 'lumen-camera',
    name: 'Lumen Action Camera',
    kind: 'camera',
    sku: 'CM-LMN-4K',
    stock: 540,
    status: 'Low',
    reserved: 87,
    incoming: 1000,
    updatedAt: '2026-09-14',
  },
]
