/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimatedIconsTableRouteImport } from './routes/animated-icons-table'
import { Route as ComparisonTableRouteImport } from './routes/comparison-table'
import { Route as DataTableRouteImport } from './routes/data-table'
import { Route as EditableTableRouteImport } from './routes/editable-table'
import { Route as FilterStateShapeTableRouteImport } from './routes/filter-state-shape-table'
import { Route as FilterToolbarTableRouteImport } from './routes/filter-toolbar-table'
import { Route as GroupedTableRouteImport } from './routes/grouped-table'
import { Route as HeatmapTableRouteImport } from './routes/heatmap-table'
import { Route as KpiTableRouteImport } from './routes/kpi-table'
import { Route as LiveStatusTableRouteImport } from './routes/live-status-table'
import { Route as MasterDetailRouteImport } from './routes/master-detail'
import { Route as PivotTableRouteImport } from './routes/pivot-table'
import { Route as ReorderTableRouteImport } from './routes/reorder-table'
import { Route as ResizableTableRouteImport } from './routes/resizable-table'
import { Route as ServerFilterRouteImport } from './routes/server-filter'
import { Route as ServerTableRouteImport } from './routes/server-table'
import { Route as ToolbarFilterTableRouteImport } from './routes/toolbar-filter-table'
import { Route as TreeReorderRouteImport } from './routes/tree-reorder'
import { Route as TreeSelectRouteImport } from './routes/tree-select'
import { Route as TreeTableRouteImport } from './routes/tree-table'
import { Route as UtilityTableRouteImport } from './routes/utility-table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimatedIconsTableRoute = AnimatedIconsTableRouteImport.update({
  id: '/animated-icons-table',
  path: '/animated-icons-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonTableRoute = ComparisonTableRouteImport.update({
  id: '/comparison-table',
  path: '/comparison-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableRoute = DataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const EditableTableRoute = EditableTableRouteImport.update({
  id: '/editable-table',
  path: '/editable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterStateShapeTableRoute = FilterStateShapeTableRouteImport.update({
  id: '/filter-state-shape-table',
  path: '/filter-state-shape-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterToolbarTableRoute = FilterToolbarTableRouteImport.update({
  id: '/filter-toolbar-table',
  path: '/filter-toolbar-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupedTableRoute = GroupedTableRouteImport.update({
  id: '/grouped-table',
  path: '/grouped-table',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapTableRoute = HeatmapTableRouteImport.update({
  id: '/heatmap-table',
  path: '/heatmap-table',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiTableRoute = KpiTableRouteImport.update({
  id: '/kpi-table',
  path: '/kpi-table',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStatusTableRoute = LiveStatusTableRouteImport.update({
  id: '/live-status-table',
  path: '/live-status-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDetailRoute = MasterDetailRouteImport.update({
  id: '/master-detail',
  path: '/master-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const PivotTableRoute = PivotTableRouteImport.update({
  id: '/pivot-table',
  path: '/pivot-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorderTableRoute = ReorderTableRouteImport.update({
  id: '/reorder-table',
  path: '/reorder-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizableTableRoute = ResizableTableRouteImport.update({
  id: '/resizable-table',
  path: '/resizable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerFilterRoute = ServerFilterRouteImport.update({
  id: '/server-filter',
  path: '/server-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerTableRoute = ServerTableRouteImport.update({
  id: '/server-table',
  path: '/server-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolbarFilterTableRoute = ToolbarFilterTableRouteImport.update({
  id: '/toolbar-filter-table',
  path: '/toolbar-filter-table',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeReorderRoute = TreeReorderRouteImport.update({
  id: '/tree-reorder',
  path: '/tree-reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeSelectRoute = TreeSelectRouteImport.update({
  id: '/tree-select',
  path: '/tree-select',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeTableRoute = TreeTableRouteImport.update({
  id: '/tree-table',
  path: '/tree-table',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityTableRoute = UtilityTableRouteImport.update({
  id: '/utility-table',
  path: '/utility-table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/data-table': typeof DataTableRoute
  '/editable-table': typeof EditableTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/pivot-table': typeof PivotTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/data-table': typeof DataTableRoute
  '/editable-table': typeof EditableTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/pivot-table': typeof PivotTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/data-table': typeof DataTableRoute
  '/editable-table': typeof EditableTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/pivot-table': typeof PivotTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animated-icons-table'
    | '/comparison-table'
    | '/data-table'
    | '/editable-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/master-detail'
    | '/pivot-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-filter'
    | '/server-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animated-icons-table'
    | '/comparison-table'
    | '/data-table'
    | '/editable-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/master-detail'
    | '/pivot-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-filter'
    | '/server-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
  id:
    | '__root__'
    | '/'
    | '/animated-icons-table'
    | '/comparison-table'
    | '/data-table'
    | '/editable-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/master-detail'
    | '/pivot-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-filter'
    | '/server-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimatedIconsTableRoute: typeof AnimatedIconsTableRoute
  ComparisonTableRoute: typeof ComparisonTableRoute
  DataTableRoute: typeof DataTableRoute
  EditableTableRoute: typeof EditableTableRoute
  FilterStateShapeTableRoute: typeof FilterStateShapeTableRoute
  FilterToolbarTableRoute: typeof FilterToolbarTableRoute
  GroupedTableRoute: typeof GroupedTableRoute
  HeatmapTableRoute: typeof HeatmapTableRoute
  KpiTableRoute: typeof KpiTableRoute
  LiveStatusTableRoute: typeof LiveStatusTableRoute
  MasterDetailRoute: typeof MasterDetailRoute
  PivotTableRoute: typeof PivotTableRoute
  ReorderTableRoute: typeof ReorderTableRoute
  ResizableTableRoute: typeof ResizableTableRoute
  ServerFilterRoute: typeof ServerFilterRoute
  ServerTableRoute: typeof ServerTableRoute
  ToolbarFilterTableRoute: typeof ToolbarFilterTableRoute
  TreeReorderRoute: typeof TreeReorderRoute
  TreeSelectRoute: typeof TreeSelectRoute
  TreeTableRoute: typeof TreeTableRoute
  UtilityTableRoute: typeof UtilityTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animated-icons-table': {
      id: '/animated-icons-table'
      path: '/animated-icons-table'
      fullPath: '/animated-icons-table'
      preLoaderRoute: typeof AnimatedIconsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison-table': {
      id: '/comparison-table'
      path: '/comparison-table'
      fullPath: '/comparison-table'
      preLoaderRoute: typeof ComparisonTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table': {
      id: '/data-table'
      path: '/data-table'
      fullPath: '/data-table'
      preLoaderRoute: typeof DataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editable-table': {
      id: '/editable-table'
      path: '/editable-table'
      fullPath: '/editable-table'
      preLoaderRoute: typeof EditableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-state-shape-table': {
      id: '/filter-state-shape-table'
      path: '/filter-state-shape-table'
      fullPath: '/filter-state-shape-table'
      preLoaderRoute: typeof FilterStateShapeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-toolbar-table': {
      id: '/filter-toolbar-table'
      path: '/filter-toolbar-table'
      fullPath: '/filter-toolbar-table'
      preLoaderRoute: typeof FilterToolbarTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grouped-table': {
      id: '/grouped-table'
      path: '/grouped-table'
      fullPath: '/grouped-table'
      preLoaderRoute: typeof GroupedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap-table': {
      id: '/heatmap-table'
      path: '/heatmap-table'
      fullPath: '/heatmap-table'
      preLoaderRoute: typeof HeatmapTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi-table': {
      id: '/kpi-table'
      path: '/kpi-table'
      fullPath: '/kpi-table'
      preLoaderRoute: typeof KpiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-status-table': {
      id: '/live-status-table'
      path: '/live-status-table'
      fullPath: '/live-status-table'
      preLoaderRoute: typeof LiveStatusTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-detail': {
      id: '/master-detail'
      path: '/master-detail'
      fullPath: '/master-detail'
      preLoaderRoute: typeof MasterDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pivot-table': {
      id: '/pivot-table'
      path: '/pivot-table'
      fullPath: '/pivot-table'
      preLoaderRoute: typeof PivotTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorder-table': {
      id: '/reorder-table'
      path: '/reorder-table'
      fullPath: '/reorder-table'
      preLoaderRoute: typeof ReorderTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resizable-table': {
      id: '/resizable-table'
      path: '/resizable-table'
      fullPath: '/resizable-table'
      preLoaderRoute: typeof ResizableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-filter': {
      id: '/server-filter'
      path: '/server-filter'
      fullPath: '/server-filter'
      preLoaderRoute: typeof ServerFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-table': {
      id: '/server-table'
      path: '/server-table'
      fullPath: '/server-table'
      preLoaderRoute: typeof ServerTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolbar-filter-table': {
      id: '/toolbar-filter-table'
      path: '/toolbar-filter-table'
      fullPath: '/toolbar-filter-table'
      preLoaderRoute: typeof ToolbarFilterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-reorder': {
      id: '/tree-reorder'
      path: '/tree-reorder'
      fullPath: '/tree-reorder'
      preLoaderRoute: typeof TreeReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-select': {
      id: '/tree-select'
      path: '/tree-select'
      fullPath: '/tree-select'
      preLoaderRoute: typeof TreeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-table': {
      id: '/tree-table'
      path: '/tree-table'
      fullPath: '/tree-table'
      preLoaderRoute: typeof TreeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility-table': {
      id: '/utility-table'
      path: '/utility-table'
      fullPath: '/utility-table'
      preLoaderRoute: typeof UtilityTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimatedIconsTableRoute: AnimatedIconsTableRoute,
  ComparisonTableRoute: ComparisonTableRoute,
  DataTableRoute: DataTableRoute,
  EditableTableRoute: EditableTableRoute,
  FilterStateShapeTableRoute: FilterStateShapeTableRoute,
  FilterToolbarTableRoute: FilterToolbarTableRoute,
  GroupedTableRoute: GroupedTableRoute,
  HeatmapTableRoute: HeatmapTableRoute,
  KpiTableRoute: KpiTableRoute,
  LiveStatusTableRoute: LiveStatusTableRoute,
  MasterDetailRoute: MasterDetailRoute,
  PivotTableRoute: PivotTableRoute,
  ReorderTableRoute: ReorderTableRoute,
  ResizableTableRoute: ResizableTableRoute,
  ServerFilterRoute: ServerFilterRoute,
  ServerTableRoute: ServerTableRoute,
  ToolbarFilterTableRoute: ToolbarFilterTableRoute,
  TreeReorderRoute: TreeReorderRoute,
  TreeSelectRoute: TreeSelectRoute,
  TreeTableRoute: TreeTableRoute,
  UtilityTableRoute: UtilityTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
