/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimatedIconsTableRouteImport } from './routes/animated-icons-table'
import { Route as AsyncActionsTableRouteImport } from './routes/async-actions-table'
import { Route as ColumnPinningTableRouteImport } from './routes/column-pinning-table'
import { Route as ComparisonTableRouteImport } from './routes/comparison-table'
import { Route as ConditionalFormattingTableRouteImport } from './routes/conditional-formatting-table'
import { Route as DataTableRouteImport } from './routes/data-table'
import { Route as DeploymentsTableRouteImport } from './routes/deployments-table'
import { Route as EditableTableRouteImport } from './routes/editable-table'
import { Route as ExportConfigTableRouteImport } from './routes/export-config-table'
import { Route as ExportSelectedTableRouteImport } from './routes/export-selected-table'
import { Route as FilterStateShapeTableRouteImport } from './routes/filter-state-shape-table'
import { Route as FilterToolbarTableRouteImport } from './routes/filter-toolbar-table'
import { Route as GroupedTableRouteImport } from './routes/grouped-table'
import { Route as HeatmapTableRouteImport } from './routes/heatmap-table'
import { Route as InfiniteScrollTableRouteImport } from './routes/infinite-scroll-table'
import { Route as InventoryAllocationTableRouteImport } from './routes/inventory-allocation-table'
import { Route as KpiTableRouteImport } from './routes/kpi-table'
import { Route as LiveStatusTableRouteImport } from './routes/live-status-table'
import { Route as LogsTableRouteImport } from './routes/logs-table'
import { Route as MasterDetailRouteImport } from './routes/master-detail'
import { Route as MigrateV9RouteImport } from './routes/migrate-v9'
import { Route as MobileCardsTableRouteImport } from './routes/mobile-cards-table'
import { Route as ParamsFilterTableRouteImport } from './routes/params-filter-table'
import { Route as PivotTableRouteImport } from './routes/pivot-table'
import { Route as ProductionDashboardTableRouteImport } from './routes/production-dashboard-table'
import { Route as ReorderTableRouteImport } from './routes/reorder-table'
import { Route as ResizableTableRouteImport } from './routes/resizable-table'
import { Route as ServerCombinedTableRouteImport } from './routes/server-combined-table'
import { Route as ServerFilterRouteImport } from './routes/server-filter'
import { Route as ServerTableRouteImport } from './routes/server-table'
import { Route as SpreadsheetTableRouteImport } from './routes/spreadsheet-table'
import { Route as ToolbarFilterTableRouteImport } from './routes/toolbar-filter-table'
import { Route as TreeReorderRouteImport } from './routes/tree-reorder'
import { Route as TreeSelectRouteImport } from './routes/tree-select'
import { Route as TreeTableRouteImport } from './routes/tree-table'
import { Route as UtilityTableRouteImport } from './routes/utility-table'
import { Route as V9IndexRouteImport } from './routes/v9/index'
import { Route as V9AnimatedIconsTableRouteImport } from './routes/v9/animated-icons-table'
import { Route as V9AsyncActionsTableRouteImport } from './routes/v9/async-actions-table'
import { Route as V9ColumnPinningTableRouteImport } from './routes/v9/column-pinning-table'
import { Route as V9ComparisonTableRouteImport } from './routes/v9/comparison-table'
import { Route as V9ConditionalFormattingTableRouteImport } from './routes/v9/conditional-formatting-table'
import { Route as V9DataTableRouteImport } from './routes/v9/data-table'
import { Route as V9DeploymentsTableRouteImport } from './routes/v9/deployments-table'
import { Route as V9EditableTableRouteImport } from './routes/v9/editable-table'
import { Route as V9ExportConfigTableRouteImport } from './routes/v9/export-config-table'
import { Route as V9ExportSelectedTableRouteImport } from './routes/v9/export-selected-table'
import { Route as V9FilterStateShapeTableRouteImport } from './routes/v9/filter-state-shape-table'
import { Route as V9FilterToolbarTableRouteImport } from './routes/v9/filter-toolbar-table'
import { Route as V9GroupedTableRouteImport } from './routes/v9/grouped-table'
import { Route as V9HeatmapTableRouteImport } from './routes/v9/heatmap-table'
import { Route as V9InfiniteScrollTableRouteImport } from './routes/v9/infinite-scroll-table'
import { Route as V9InventoryAllocationTableRouteImport } from './routes/v9/inventory-allocation-table'
import { Route as V9KpiTableRouteImport } from './routes/v9/kpi-table'
import { Route as V9LiveStatusTableRouteImport } from './routes/v9/live-status-table'
import { Route as V9LogsTableRouteImport } from './routes/v9/logs-table'
import { Route as V9MasterDetailRouteImport } from './routes/v9/master-detail'
import { Route as V9MobileCardsTableRouteImport } from './routes/v9/mobile-cards-table'
import { Route as V9ParamsFilterTableRouteImport } from './routes/v9/params-filter-table'
import { Route as V9PivotTableRouteImport } from './routes/v9/pivot-table'
import { Route as V9ProductionDashboardTableRouteImport } from './routes/v9/production-dashboard-table'
import { Route as V9ReorderTableRouteImport } from './routes/v9/reorder-table'
import { Route as V9ResizableTableRouteImport } from './routes/v9/resizable-table'
import { Route as V9ServerCombinedTableRouteImport } from './routes/v9/server-combined-table'
import { Route as V9ServerFilterRouteImport } from './routes/v9/server-filter'
import { Route as V9ServerTableRouteImport } from './routes/v9/server-table'
import { Route as V9SpreadsheetTableRouteImport } from './routes/v9/spreadsheet-table'
import { Route as V9ToolbarFilterTableRouteImport } from './routes/v9/toolbar-filter-table'
import { Route as V9TreeReorderRouteImport } from './routes/v9/tree-reorder'
import { Route as V9TreeSelectRouteImport } from './routes/v9/tree-select'
import { Route as V9TreeTableRouteImport } from './routes/v9/tree-table'
import { Route as V9UtilityTableRouteImport } from './routes/v9/utility-table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimatedIconsTableRoute = AnimatedIconsTableRouteImport.update({
  id: '/animated-icons-table',
  path: '/animated-icons-table',
  getParentRoute: () => rootRouteImport,
} as any)
const AsyncActionsTableRoute = AsyncActionsTableRouteImport.update({
  id: '/async-actions-table',
  path: '/async-actions-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnPinningTableRoute = ColumnPinningTableRouteImport.update({
  id: '/column-pinning-table',
  path: '/column-pinning-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonTableRoute = ComparisonTableRouteImport.update({
  id: '/comparison-table',
  path: '/comparison-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionalFormattingTableRoute =
  ConditionalFormattingTableRouteImport.update({
    id: '/conditional-formatting-table',
    path: '/conditional-formatting-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataTableRoute = DataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsTableRoute = DeploymentsTableRouteImport.update({
  id: '/deployments-table',
  path: '/deployments-table',
  getParentRoute: () => rootRouteImport,
} as any)
const EditableTableRoute = EditableTableRouteImport.update({
  id: '/editable-table',
  path: '/editable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportConfigTableRoute = ExportConfigTableRouteImport.update({
  id: '/export-config-table',
  path: '/export-config-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportSelectedTableRoute = ExportSelectedTableRouteImport.update({
  id: '/export-selected-table',
  path: '/export-selected-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterStateShapeTableRoute = FilterStateShapeTableRouteImport.update({
  id: '/filter-state-shape-table',
  path: '/filter-state-shape-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterToolbarTableRoute = FilterToolbarTableRouteImport.update({
  id: '/filter-toolbar-table',
  path: '/filter-toolbar-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupedTableRoute = GroupedTableRouteImport.update({
  id: '/grouped-table',
  path: '/grouped-table',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapTableRoute = HeatmapTableRouteImport.update({
  id: '/heatmap-table',
  path: '/heatmap-table',
  getParentRoute: () => rootRouteImport,
} as any)
const InfiniteScrollTableRoute = InfiniteScrollTableRouteImport.update({
  id: '/infinite-scroll-table',
  path: '/infinite-scroll-table',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAllocationTableRoute =
  InventoryAllocationTableRouteImport.update({
    id: '/inventory-allocation-table',
    path: '/inventory-allocation-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const KpiTableRoute = KpiTableRouteImport.update({
  id: '/kpi-table',
  path: '/kpi-table',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStatusTableRoute = LiveStatusTableRouteImport.update({
  id: '/live-status-table',
  path: '/live-status-table',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsTableRoute = LogsTableRouteImport.update({
  id: '/logs-table',
  path: '/logs-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDetailRoute = MasterDetailRouteImport.update({
  id: '/master-detail',
  path: '/master-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateV9Route = MigrateV9RouteImport.update({
  id: '/migrate-v9',
  path: '/migrate-v9',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileCardsTableRoute = MobileCardsTableRouteImport.update({
  id: '/mobile-cards-table',
  path: '/mobile-cards-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ParamsFilterTableRoute = ParamsFilterTableRouteImport.update({
  id: '/params-filter-table',
  path: '/params-filter-table',
  getParentRoute: () => rootRouteImport,
} as any)
const PivotTableRoute = PivotTableRouteImport.update({
  id: '/pivot-table',
  path: '/pivot-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionDashboardTableRoute =
  ProductionDashboardTableRouteImport.update({
    id: '/production-dashboard-table',
    path: '/production-dashboard-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReorderTableRoute = ReorderTableRouteImport.update({
  id: '/reorder-table',
  path: '/reorder-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizableTableRoute = ResizableTableRouteImport.update({
  id: '/resizable-table',
  path: '/resizable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerCombinedTableRoute = ServerCombinedTableRouteImport.update({
  id: '/server-combined-table',
  path: '/server-combined-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerFilterRoute = ServerFilterRouteImport.update({
  id: '/server-filter',
  path: '/server-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerTableRoute = ServerTableRouteImport.update({
  id: '/server-table',
  path: '/server-table',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsheetTableRoute = SpreadsheetTableRouteImport.update({
  id: '/spreadsheet-table',
  path: '/spreadsheet-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolbarFilterTableRoute = ToolbarFilterTableRouteImport.update({
  id: '/toolbar-filter-table',
  path: '/toolbar-filter-table',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeReorderRoute = TreeReorderRouteImport.update({
  id: '/tree-reorder',
  path: '/tree-reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeSelectRoute = TreeSelectRouteImport.update({
  id: '/tree-select',
  path: '/tree-select',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeTableRoute = TreeTableRouteImport.update({
  id: '/tree-table',
  path: '/tree-table',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityTableRoute = UtilityTableRouteImport.update({
  id: '/utility-table',
  path: '/utility-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9IndexRoute = V9IndexRouteImport.update({
  id: '/v9/',
  path: '/v9/',
  getParentRoute: () => rootRouteImport,
} as any)
const V9AnimatedIconsTableRoute = V9AnimatedIconsTableRouteImport.update({
  id: '/v9/animated-icons-table',
  path: '/v9/animated-icons-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9AsyncActionsTableRoute = V9AsyncActionsTableRouteImport.update({
  id: '/v9/async-actions-table',
  path: '/v9/async-actions-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ColumnPinningTableRoute = V9ColumnPinningTableRouteImport.update({
  id: '/v9/column-pinning-table',
  path: '/v9/column-pinning-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ComparisonTableRoute = V9ComparisonTableRouteImport.update({
  id: '/v9/comparison-table',
  path: '/v9/comparison-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ConditionalFormattingTableRoute =
  V9ConditionalFormattingTableRouteImport.update({
    id: '/v9/conditional-formatting-table',
    path: '/v9/conditional-formatting-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const V9DataTableRoute = V9DataTableRouteImport.update({
  id: '/v9/data-table',
  path: '/v9/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9DeploymentsTableRoute = V9DeploymentsTableRouteImport.update({
  id: '/v9/deployments-table',
  path: '/v9/deployments-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9EditableTableRoute = V9EditableTableRouteImport.update({
  id: '/v9/editable-table',
  path: '/v9/editable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ExportConfigTableRoute = V9ExportConfigTableRouteImport.update({
  id: '/v9/export-config-table',
  path: '/v9/export-config-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ExportSelectedTableRoute = V9ExportSelectedTableRouteImport.update({
  id: '/v9/export-selected-table',
  path: '/v9/export-selected-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9FilterStateShapeTableRoute = V9FilterStateShapeTableRouteImport.update({
  id: '/v9/filter-state-shape-table',
  path: '/v9/filter-state-shape-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9FilterToolbarTableRoute = V9FilterToolbarTableRouteImport.update({
  id: '/v9/filter-toolbar-table',
  path: '/v9/filter-toolbar-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9GroupedTableRoute = V9GroupedTableRouteImport.update({
  id: '/v9/grouped-table',
  path: '/v9/grouped-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9HeatmapTableRoute = V9HeatmapTableRouteImport.update({
  id: '/v9/heatmap-table',
  path: '/v9/heatmap-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9InfiniteScrollTableRoute = V9InfiniteScrollTableRouteImport.update({
  id: '/v9/infinite-scroll-table',
  path: '/v9/infinite-scroll-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9InventoryAllocationTableRoute =
  V9InventoryAllocationTableRouteImport.update({
    id: '/v9/inventory-allocation-table',
    path: '/v9/inventory-allocation-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const V9KpiTableRoute = V9KpiTableRouteImport.update({
  id: '/v9/kpi-table',
  path: '/v9/kpi-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9LiveStatusTableRoute = V9LiveStatusTableRouteImport.update({
  id: '/v9/live-status-table',
  path: '/v9/live-status-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9LogsTableRoute = V9LogsTableRouteImport.update({
  id: '/v9/logs-table',
  path: '/v9/logs-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9MasterDetailRoute = V9MasterDetailRouteImport.update({
  id: '/v9/master-detail',
  path: '/v9/master-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const V9MobileCardsTableRoute = V9MobileCardsTableRouteImport.update({
  id: '/v9/mobile-cards-table',
  path: '/v9/mobile-cards-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ParamsFilterTableRoute = V9ParamsFilterTableRouteImport.update({
  id: '/v9/params-filter-table',
  path: '/v9/params-filter-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9PivotTableRoute = V9PivotTableRouteImport.update({
  id: '/v9/pivot-table',
  path: '/v9/pivot-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ProductionDashboardTableRoute =
  V9ProductionDashboardTableRouteImport.update({
    id: '/v9/production-dashboard-table',
    path: '/v9/production-dashboard-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const V9ReorderTableRoute = V9ReorderTableRouteImport.update({
  id: '/v9/reorder-table',
  path: '/v9/reorder-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ResizableTableRoute = V9ResizableTableRouteImport.update({
  id: '/v9/resizable-table',
  path: '/v9/resizable-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ServerCombinedTableRoute = V9ServerCombinedTableRouteImport.update({
  id: '/v9/server-combined-table',
  path: '/v9/server-combined-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ServerFilterRoute = V9ServerFilterRouteImport.update({
  id: '/v9/server-filter',
  path: '/v9/server-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ServerTableRoute = V9ServerTableRouteImport.update({
  id: '/v9/server-table',
  path: '/v9/server-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9SpreadsheetTableRoute = V9SpreadsheetTableRouteImport.update({
  id: '/v9/spreadsheet-table',
  path: '/v9/spreadsheet-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9ToolbarFilterTableRoute = V9ToolbarFilterTableRouteImport.update({
  id: '/v9/toolbar-filter-table',
  path: '/v9/toolbar-filter-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9TreeReorderRoute = V9TreeReorderRouteImport.update({
  id: '/v9/tree-reorder',
  path: '/v9/tree-reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const V9TreeSelectRoute = V9TreeSelectRouteImport.update({
  id: '/v9/tree-select',
  path: '/v9/tree-select',
  getParentRoute: () => rootRouteImport,
} as any)
const V9TreeTableRoute = V9TreeTableRouteImport.update({
  id: '/v9/tree-table',
  path: '/v9/tree-table',
  getParentRoute: () => rootRouteImport,
} as any)
const V9UtilityTableRoute = V9UtilityTableRouteImport.update({
  id: '/v9/utility-table',
  path: '/v9/utility-table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/async-actions-table': typeof AsyncActionsTableRoute
  '/column-pinning-table': typeof ColumnPinningTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/conditional-formatting-table': typeof ConditionalFormattingTableRoute
  '/data-table': typeof DataTableRoute
  '/deployments-table': typeof DeploymentsTableRoute
  '/editable-table': typeof EditableTableRoute
  '/export-config-table': typeof ExportConfigTableRoute
  '/export-selected-table': typeof ExportSelectedTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/infinite-scroll-table': typeof InfiniteScrollTableRoute
  '/inventory-allocation-table': typeof InventoryAllocationTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/logs-table': typeof LogsTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/migrate-v9': typeof MigrateV9Route
  '/mobile-cards-table': typeof MobileCardsTableRoute
  '/params-filter-table': typeof ParamsFilterTableRoute
  '/pivot-table': typeof PivotTableRoute
  '/production-dashboard-table': typeof ProductionDashboardTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-combined-table': typeof ServerCombinedTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/spreadsheet-table': typeof SpreadsheetTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
  '/v9/animated-icons-table': typeof V9AnimatedIconsTableRoute
  '/v9/async-actions-table': typeof V9AsyncActionsTableRoute
  '/v9/column-pinning-table': typeof V9ColumnPinningTableRoute
  '/v9/comparison-table': typeof V9ComparisonTableRoute
  '/v9/conditional-formatting-table': typeof V9ConditionalFormattingTableRoute
  '/v9/data-table': typeof V9DataTableRoute
  '/v9/deployments-table': typeof V9DeploymentsTableRoute
  '/v9/editable-table': typeof V9EditableTableRoute
  '/v9/export-config-table': typeof V9ExportConfigTableRoute
  '/v9/export-selected-table': typeof V9ExportSelectedTableRoute
  '/v9/filter-state-shape-table': typeof V9FilterStateShapeTableRoute
  '/v9/filter-toolbar-table': typeof V9FilterToolbarTableRoute
  '/v9/grouped-table': typeof V9GroupedTableRoute
  '/v9/heatmap-table': typeof V9HeatmapTableRoute
  '/v9/infinite-scroll-table': typeof V9InfiniteScrollTableRoute
  '/v9/inventory-allocation-table': typeof V9InventoryAllocationTableRoute
  '/v9/kpi-table': typeof V9KpiTableRoute
  '/v9/live-status-table': typeof V9LiveStatusTableRoute
  '/v9/logs-table': typeof V9LogsTableRoute
  '/v9/master-detail': typeof V9MasterDetailRoute
  '/v9/mobile-cards-table': typeof V9MobileCardsTableRoute
  '/v9/params-filter-table': typeof V9ParamsFilterTableRoute
  '/v9/pivot-table': typeof V9PivotTableRoute
  '/v9/production-dashboard-table': typeof V9ProductionDashboardTableRoute
  '/v9/reorder-table': typeof V9ReorderTableRoute
  '/v9/resizable-table': typeof V9ResizableTableRoute
  '/v9/server-combined-table': typeof V9ServerCombinedTableRoute
  '/v9/server-filter': typeof V9ServerFilterRoute
  '/v9/server-table': typeof V9ServerTableRoute
  '/v9/spreadsheet-table': typeof V9SpreadsheetTableRoute
  '/v9/toolbar-filter-table': typeof V9ToolbarFilterTableRoute
  '/v9/tree-reorder': typeof V9TreeReorderRoute
  '/v9/tree-select': typeof V9TreeSelectRoute
  '/v9/tree-table': typeof V9TreeTableRoute
  '/v9/utility-table': typeof V9UtilityTableRoute
  '/v9/': typeof V9IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/async-actions-table': typeof AsyncActionsTableRoute
  '/column-pinning-table': typeof ColumnPinningTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/conditional-formatting-table': typeof ConditionalFormattingTableRoute
  '/data-table': typeof DataTableRoute
  '/deployments-table': typeof DeploymentsTableRoute
  '/editable-table': typeof EditableTableRoute
  '/export-config-table': typeof ExportConfigTableRoute
  '/export-selected-table': typeof ExportSelectedTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/infinite-scroll-table': typeof InfiniteScrollTableRoute
  '/inventory-allocation-table': typeof InventoryAllocationTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/logs-table': typeof LogsTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/migrate-v9': typeof MigrateV9Route
  '/mobile-cards-table': typeof MobileCardsTableRoute
  '/params-filter-table': typeof ParamsFilterTableRoute
  '/pivot-table': typeof PivotTableRoute
  '/production-dashboard-table': typeof ProductionDashboardTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-combined-table': typeof ServerCombinedTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/spreadsheet-table': typeof SpreadsheetTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
  '/v9/animated-icons-table': typeof V9AnimatedIconsTableRoute
  '/v9/async-actions-table': typeof V9AsyncActionsTableRoute
  '/v9/column-pinning-table': typeof V9ColumnPinningTableRoute
  '/v9/comparison-table': typeof V9ComparisonTableRoute
  '/v9/conditional-formatting-table': typeof V9ConditionalFormattingTableRoute
  '/v9/data-table': typeof V9DataTableRoute
  '/v9/deployments-table': typeof V9DeploymentsTableRoute
  '/v9/editable-table': typeof V9EditableTableRoute
  '/v9/export-config-table': typeof V9ExportConfigTableRoute
  '/v9/export-selected-table': typeof V9ExportSelectedTableRoute
  '/v9/filter-state-shape-table': typeof V9FilterStateShapeTableRoute
  '/v9/filter-toolbar-table': typeof V9FilterToolbarTableRoute
  '/v9/grouped-table': typeof V9GroupedTableRoute
  '/v9/heatmap-table': typeof V9HeatmapTableRoute
  '/v9/infinite-scroll-table': typeof V9InfiniteScrollTableRoute
  '/v9/inventory-allocation-table': typeof V9InventoryAllocationTableRoute
  '/v9/kpi-table': typeof V9KpiTableRoute
  '/v9/live-status-table': typeof V9LiveStatusTableRoute
  '/v9/logs-table': typeof V9LogsTableRoute
  '/v9/master-detail': typeof V9MasterDetailRoute
  '/v9/mobile-cards-table': typeof V9MobileCardsTableRoute
  '/v9/params-filter-table': typeof V9ParamsFilterTableRoute
  '/v9/pivot-table': typeof V9PivotTableRoute
  '/v9/production-dashboard-table': typeof V9ProductionDashboardTableRoute
  '/v9/reorder-table': typeof V9ReorderTableRoute
  '/v9/resizable-table': typeof V9ResizableTableRoute
  '/v9/server-combined-table': typeof V9ServerCombinedTableRoute
  '/v9/server-filter': typeof V9ServerFilterRoute
  '/v9/server-table': typeof V9ServerTableRoute
  '/v9/spreadsheet-table': typeof V9SpreadsheetTableRoute
  '/v9/toolbar-filter-table': typeof V9ToolbarFilterTableRoute
  '/v9/tree-reorder': typeof V9TreeReorderRoute
  '/v9/tree-select': typeof V9TreeSelectRoute
  '/v9/tree-table': typeof V9TreeTableRoute
  '/v9/utility-table': typeof V9UtilityTableRoute
  '/v9': typeof V9IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animated-icons-table': typeof AnimatedIconsTableRoute
  '/async-actions-table': typeof AsyncActionsTableRoute
  '/column-pinning-table': typeof ColumnPinningTableRoute
  '/comparison-table': typeof ComparisonTableRoute
  '/conditional-formatting-table': typeof ConditionalFormattingTableRoute
  '/data-table': typeof DataTableRoute
  '/deployments-table': typeof DeploymentsTableRoute
  '/editable-table': typeof EditableTableRoute
  '/export-config-table': typeof ExportConfigTableRoute
  '/export-selected-table': typeof ExportSelectedTableRoute
  '/filter-state-shape-table': typeof FilterStateShapeTableRoute
  '/filter-toolbar-table': typeof FilterToolbarTableRoute
  '/grouped-table': typeof GroupedTableRoute
  '/heatmap-table': typeof HeatmapTableRoute
  '/infinite-scroll-table': typeof InfiniteScrollTableRoute
  '/inventory-allocation-table': typeof InventoryAllocationTableRoute
  '/kpi-table': typeof KpiTableRoute
  '/live-status-table': typeof LiveStatusTableRoute
  '/logs-table': typeof LogsTableRoute
  '/master-detail': typeof MasterDetailRoute
  '/migrate-v9': typeof MigrateV9Route
  '/mobile-cards-table': typeof MobileCardsTableRoute
  '/params-filter-table': typeof ParamsFilterTableRoute
  '/pivot-table': typeof PivotTableRoute
  '/production-dashboard-table': typeof ProductionDashboardTableRoute
  '/reorder-table': typeof ReorderTableRoute
  '/resizable-table': typeof ResizableTableRoute
  '/server-combined-table': typeof ServerCombinedTableRoute
  '/server-filter': typeof ServerFilterRoute
  '/server-table': typeof ServerTableRoute
  '/spreadsheet-table': typeof SpreadsheetTableRoute
  '/toolbar-filter-table': typeof ToolbarFilterTableRoute
  '/tree-reorder': typeof TreeReorderRoute
  '/tree-select': typeof TreeSelectRoute
  '/tree-table': typeof TreeTableRoute
  '/utility-table': typeof UtilityTableRoute
  '/v9/animated-icons-table': typeof V9AnimatedIconsTableRoute
  '/v9/async-actions-table': typeof V9AsyncActionsTableRoute
  '/v9/column-pinning-table': typeof V9ColumnPinningTableRoute
  '/v9/comparison-table': typeof V9ComparisonTableRoute
  '/v9/conditional-formatting-table': typeof V9ConditionalFormattingTableRoute
  '/v9/data-table': typeof V9DataTableRoute
  '/v9/deployments-table': typeof V9DeploymentsTableRoute
  '/v9/editable-table': typeof V9EditableTableRoute
  '/v9/export-config-table': typeof V9ExportConfigTableRoute
  '/v9/export-selected-table': typeof V9ExportSelectedTableRoute
  '/v9/filter-state-shape-table': typeof V9FilterStateShapeTableRoute
  '/v9/filter-toolbar-table': typeof V9FilterToolbarTableRoute
  '/v9/grouped-table': typeof V9GroupedTableRoute
  '/v9/heatmap-table': typeof V9HeatmapTableRoute
  '/v9/infinite-scroll-table': typeof V9InfiniteScrollTableRoute
  '/v9/inventory-allocation-table': typeof V9InventoryAllocationTableRoute
  '/v9/kpi-table': typeof V9KpiTableRoute
  '/v9/live-status-table': typeof V9LiveStatusTableRoute
  '/v9/logs-table': typeof V9LogsTableRoute
  '/v9/master-detail': typeof V9MasterDetailRoute
  '/v9/mobile-cards-table': typeof V9MobileCardsTableRoute
  '/v9/params-filter-table': typeof V9ParamsFilterTableRoute
  '/v9/pivot-table': typeof V9PivotTableRoute
  '/v9/production-dashboard-table': typeof V9ProductionDashboardTableRoute
  '/v9/reorder-table': typeof V9ReorderTableRoute
  '/v9/resizable-table': typeof V9ResizableTableRoute
  '/v9/server-combined-table': typeof V9ServerCombinedTableRoute
  '/v9/server-filter': typeof V9ServerFilterRoute
  '/v9/server-table': typeof V9ServerTableRoute
  '/v9/spreadsheet-table': typeof V9SpreadsheetTableRoute
  '/v9/toolbar-filter-table': typeof V9ToolbarFilterTableRoute
  '/v9/tree-reorder': typeof V9TreeReorderRoute
  '/v9/tree-select': typeof V9TreeSelectRoute
  '/v9/tree-table': typeof V9TreeTableRoute
  '/v9/utility-table': typeof V9UtilityTableRoute
  '/v9/': typeof V9IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animated-icons-table'
    | '/async-actions-table'
    | '/column-pinning-table'
    | '/comparison-table'
    | '/conditional-formatting-table'
    | '/data-table'
    | '/deployments-table'
    | '/editable-table'
    | '/export-config-table'
    | '/export-selected-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/infinite-scroll-table'
    | '/inventory-allocation-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/logs-table'
    | '/master-detail'
    | '/migrate-v9'
    | '/mobile-cards-table'
    | '/params-filter-table'
    | '/pivot-table'
    | '/production-dashboard-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-combined-table'
    | '/server-filter'
    | '/server-table'
    | '/spreadsheet-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
    | '/v9/animated-icons-table'
    | '/v9/async-actions-table'
    | '/v9/column-pinning-table'
    | '/v9/comparison-table'
    | '/v9/conditional-formatting-table'
    | '/v9/data-table'
    | '/v9/deployments-table'
    | '/v9/editable-table'
    | '/v9/export-config-table'
    | '/v9/export-selected-table'
    | '/v9/filter-state-shape-table'
    | '/v9/filter-toolbar-table'
    | '/v9/grouped-table'
    | '/v9/heatmap-table'
    | '/v9/infinite-scroll-table'
    | '/v9/inventory-allocation-table'
    | '/v9/kpi-table'
    | '/v9/live-status-table'
    | '/v9/logs-table'
    | '/v9/master-detail'
    | '/v9/mobile-cards-table'
    | '/v9/params-filter-table'
    | '/v9/pivot-table'
    | '/v9/production-dashboard-table'
    | '/v9/reorder-table'
    | '/v9/resizable-table'
    | '/v9/server-combined-table'
    | '/v9/server-filter'
    | '/v9/server-table'
    | '/v9/spreadsheet-table'
    | '/v9/toolbar-filter-table'
    | '/v9/tree-reorder'
    | '/v9/tree-select'
    | '/v9/tree-table'
    | '/v9/utility-table'
    | '/v9/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animated-icons-table'
    | '/async-actions-table'
    | '/column-pinning-table'
    | '/comparison-table'
    | '/conditional-formatting-table'
    | '/data-table'
    | '/deployments-table'
    | '/editable-table'
    | '/export-config-table'
    | '/export-selected-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/infinite-scroll-table'
    | '/inventory-allocation-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/logs-table'
    | '/master-detail'
    | '/migrate-v9'
    | '/mobile-cards-table'
    | '/params-filter-table'
    | '/pivot-table'
    | '/production-dashboard-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-combined-table'
    | '/server-filter'
    | '/server-table'
    | '/spreadsheet-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
    | '/v9/animated-icons-table'
    | '/v9/async-actions-table'
    | '/v9/column-pinning-table'
    | '/v9/comparison-table'
    | '/v9/conditional-formatting-table'
    | '/v9/data-table'
    | '/v9/deployments-table'
    | '/v9/editable-table'
    | '/v9/export-config-table'
    | '/v9/export-selected-table'
    | '/v9/filter-state-shape-table'
    | '/v9/filter-toolbar-table'
    | '/v9/grouped-table'
    | '/v9/heatmap-table'
    | '/v9/infinite-scroll-table'
    | '/v9/inventory-allocation-table'
    | '/v9/kpi-table'
    | '/v9/live-status-table'
    | '/v9/logs-table'
    | '/v9/master-detail'
    | '/v9/mobile-cards-table'
    | '/v9/params-filter-table'
    | '/v9/pivot-table'
    | '/v9/production-dashboard-table'
    | '/v9/reorder-table'
    | '/v9/resizable-table'
    | '/v9/server-combined-table'
    | '/v9/server-filter'
    | '/v9/server-table'
    | '/v9/spreadsheet-table'
    | '/v9/toolbar-filter-table'
    | '/v9/tree-reorder'
    | '/v9/tree-select'
    | '/v9/tree-table'
    | '/v9/utility-table'
    | '/v9'
  id:
    | '__root__'
    | '/'
    | '/animated-icons-table'
    | '/async-actions-table'
    | '/column-pinning-table'
    | '/comparison-table'
    | '/conditional-formatting-table'
    | '/data-table'
    | '/deployments-table'
    | '/editable-table'
    | '/export-config-table'
    | '/export-selected-table'
    | '/filter-state-shape-table'
    | '/filter-toolbar-table'
    | '/grouped-table'
    | '/heatmap-table'
    | '/infinite-scroll-table'
    | '/inventory-allocation-table'
    | '/kpi-table'
    | '/live-status-table'
    | '/logs-table'
    | '/master-detail'
    | '/migrate-v9'
    | '/mobile-cards-table'
    | '/params-filter-table'
    | '/pivot-table'
    | '/production-dashboard-table'
    | '/reorder-table'
    | '/resizable-table'
    | '/server-combined-table'
    | '/server-filter'
    | '/server-table'
    | '/spreadsheet-table'
    | '/toolbar-filter-table'
    | '/tree-reorder'
    | '/tree-select'
    | '/tree-table'
    | '/utility-table'
    | '/v9/animated-icons-table'
    | '/v9/async-actions-table'
    | '/v9/column-pinning-table'
    | '/v9/comparison-table'
    | '/v9/conditional-formatting-table'
    | '/v9/data-table'
    | '/v9/deployments-table'
    | '/v9/editable-table'
    | '/v9/export-config-table'
    | '/v9/export-selected-table'
    | '/v9/filter-state-shape-table'
    | '/v9/filter-toolbar-table'
    | '/v9/grouped-table'
    | '/v9/heatmap-table'
    | '/v9/infinite-scroll-table'
    | '/v9/inventory-allocation-table'
    | '/v9/kpi-table'
    | '/v9/live-status-table'
    | '/v9/logs-table'
    | '/v9/master-detail'
    | '/v9/mobile-cards-table'
    | '/v9/params-filter-table'
    | '/v9/pivot-table'
    | '/v9/production-dashboard-table'
    | '/v9/reorder-table'
    | '/v9/resizable-table'
    | '/v9/server-combined-table'
    | '/v9/server-filter'
    | '/v9/server-table'
    | '/v9/spreadsheet-table'
    | '/v9/toolbar-filter-table'
    | '/v9/tree-reorder'
    | '/v9/tree-select'
    | '/v9/tree-table'
    | '/v9/utility-table'
    | '/v9/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimatedIconsTableRoute: typeof AnimatedIconsTableRoute
  AsyncActionsTableRoute: typeof AsyncActionsTableRoute
  ColumnPinningTableRoute: typeof ColumnPinningTableRoute
  ComparisonTableRoute: typeof ComparisonTableRoute
  ConditionalFormattingTableRoute: typeof ConditionalFormattingTableRoute
  DataTableRoute: typeof DataTableRoute
  DeploymentsTableRoute: typeof DeploymentsTableRoute
  EditableTableRoute: typeof EditableTableRoute
  ExportConfigTableRoute: typeof ExportConfigTableRoute
  ExportSelectedTableRoute: typeof ExportSelectedTableRoute
  FilterStateShapeTableRoute: typeof FilterStateShapeTableRoute
  FilterToolbarTableRoute: typeof FilterToolbarTableRoute
  GroupedTableRoute: typeof GroupedTableRoute
  HeatmapTableRoute: typeof HeatmapTableRoute
  InfiniteScrollTableRoute: typeof InfiniteScrollTableRoute
  InventoryAllocationTableRoute: typeof InventoryAllocationTableRoute
  KpiTableRoute: typeof KpiTableRoute
  LiveStatusTableRoute: typeof LiveStatusTableRoute
  LogsTableRoute: typeof LogsTableRoute
  MasterDetailRoute: typeof MasterDetailRoute
  MigrateV9Route: typeof MigrateV9Route
  MobileCardsTableRoute: typeof MobileCardsTableRoute
  ParamsFilterTableRoute: typeof ParamsFilterTableRoute
  PivotTableRoute: typeof PivotTableRoute
  ProductionDashboardTableRoute: typeof ProductionDashboardTableRoute
  ReorderTableRoute: typeof ReorderTableRoute
  ResizableTableRoute: typeof ResizableTableRoute
  ServerCombinedTableRoute: typeof ServerCombinedTableRoute
  ServerFilterRoute: typeof ServerFilterRoute
  ServerTableRoute: typeof ServerTableRoute
  SpreadsheetTableRoute: typeof SpreadsheetTableRoute
  ToolbarFilterTableRoute: typeof ToolbarFilterTableRoute
  TreeReorderRoute: typeof TreeReorderRoute
  TreeSelectRoute: typeof TreeSelectRoute
  TreeTableRoute: typeof TreeTableRoute
  UtilityTableRoute: typeof UtilityTableRoute
  V9AnimatedIconsTableRoute: typeof V9AnimatedIconsTableRoute
  V9AsyncActionsTableRoute: typeof V9AsyncActionsTableRoute
  V9ColumnPinningTableRoute: typeof V9ColumnPinningTableRoute
  V9ComparisonTableRoute: typeof V9ComparisonTableRoute
  V9ConditionalFormattingTableRoute: typeof V9ConditionalFormattingTableRoute
  V9DataTableRoute: typeof V9DataTableRoute
  V9DeploymentsTableRoute: typeof V9DeploymentsTableRoute
  V9EditableTableRoute: typeof V9EditableTableRoute
  V9ExportConfigTableRoute: typeof V9ExportConfigTableRoute
  V9ExportSelectedTableRoute: typeof V9ExportSelectedTableRoute
  V9FilterStateShapeTableRoute: typeof V9FilterStateShapeTableRoute
  V9FilterToolbarTableRoute: typeof V9FilterToolbarTableRoute
  V9GroupedTableRoute: typeof V9GroupedTableRoute
  V9HeatmapTableRoute: typeof V9HeatmapTableRoute
  V9InfiniteScrollTableRoute: typeof V9InfiniteScrollTableRoute
  V9InventoryAllocationTableRoute: typeof V9InventoryAllocationTableRoute
  V9KpiTableRoute: typeof V9KpiTableRoute
  V9LiveStatusTableRoute: typeof V9LiveStatusTableRoute
  V9LogsTableRoute: typeof V9LogsTableRoute
  V9MasterDetailRoute: typeof V9MasterDetailRoute
  V9MobileCardsTableRoute: typeof V9MobileCardsTableRoute
  V9ParamsFilterTableRoute: typeof V9ParamsFilterTableRoute
  V9PivotTableRoute: typeof V9PivotTableRoute
  V9ProductionDashboardTableRoute: typeof V9ProductionDashboardTableRoute
  V9ReorderTableRoute: typeof V9ReorderTableRoute
  V9ResizableTableRoute: typeof V9ResizableTableRoute
  V9ServerCombinedTableRoute: typeof V9ServerCombinedTableRoute
  V9ServerFilterRoute: typeof V9ServerFilterRoute
  V9ServerTableRoute: typeof V9ServerTableRoute
  V9SpreadsheetTableRoute: typeof V9SpreadsheetTableRoute
  V9ToolbarFilterTableRoute: typeof V9ToolbarFilterTableRoute
  V9TreeReorderRoute: typeof V9TreeReorderRoute
  V9TreeSelectRoute: typeof V9TreeSelectRoute
  V9TreeTableRoute: typeof V9TreeTableRoute
  V9UtilityTableRoute: typeof V9UtilityTableRoute
  V9IndexRoute: typeof V9IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animated-icons-table': {
      id: '/animated-icons-table'
      path: '/animated-icons-table'
      fullPath: '/animated-icons-table'
      preLoaderRoute: typeof AnimatedIconsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/async-actions-table': {
      id: '/async-actions-table'
      path: '/async-actions-table'
      fullPath: '/async-actions-table'
      preLoaderRoute: typeof AsyncActionsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column-pinning-table': {
      id: '/column-pinning-table'
      path: '/column-pinning-table'
      fullPath: '/column-pinning-table'
      preLoaderRoute: typeof ColumnPinningTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison-table': {
      id: '/comparison-table'
      path: '/comparison-table'
      fullPath: '/comparison-table'
      preLoaderRoute: typeof ComparisonTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditional-formatting-table': {
      id: '/conditional-formatting-table'
      path: '/conditional-formatting-table'
      fullPath: '/conditional-formatting-table'
      preLoaderRoute: typeof ConditionalFormattingTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table': {
      id: '/data-table'
      path: '/data-table'
      fullPath: '/data-table'
      preLoaderRoute: typeof DataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments-table': {
      id: '/deployments-table'
      path: '/deployments-table'
      fullPath: '/deployments-table'
      preLoaderRoute: typeof DeploymentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editable-table': {
      id: '/editable-table'
      path: '/editable-table'
      fullPath: '/editable-table'
      preLoaderRoute: typeof EditableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-config-table': {
      id: '/export-config-table'
      path: '/export-config-table'
      fullPath: '/export-config-table'
      preLoaderRoute: typeof ExportConfigTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-selected-table': {
      id: '/export-selected-table'
      path: '/export-selected-table'
      fullPath: '/export-selected-table'
      preLoaderRoute: typeof ExportSelectedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-state-shape-table': {
      id: '/filter-state-shape-table'
      path: '/filter-state-shape-table'
      fullPath: '/filter-state-shape-table'
      preLoaderRoute: typeof FilterStateShapeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-toolbar-table': {
      id: '/filter-toolbar-table'
      path: '/filter-toolbar-table'
      fullPath: '/filter-toolbar-table'
      preLoaderRoute: typeof FilterToolbarTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grouped-table': {
      id: '/grouped-table'
      path: '/grouped-table'
      fullPath: '/grouped-table'
      preLoaderRoute: typeof GroupedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap-table': {
      id: '/heatmap-table'
      path: '/heatmap-table'
      fullPath: '/heatmap-table'
      preLoaderRoute: typeof HeatmapTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinite-scroll-table': {
      id: '/infinite-scroll-table'
      path: '/infinite-scroll-table'
      fullPath: '/infinite-scroll-table'
      preLoaderRoute: typeof InfiniteScrollTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-allocation-table': {
      id: '/inventory-allocation-table'
      path: '/inventory-allocation-table'
      fullPath: '/inventory-allocation-table'
      preLoaderRoute: typeof InventoryAllocationTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi-table': {
      id: '/kpi-table'
      path: '/kpi-table'
      fullPath: '/kpi-table'
      preLoaderRoute: typeof KpiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-status-table': {
      id: '/live-status-table'
      path: '/live-status-table'
      fullPath: '/live-status-table'
      preLoaderRoute: typeof LiveStatusTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs-table': {
      id: '/logs-table'
      path: '/logs-table'
      fullPath: '/logs-table'
      preLoaderRoute: typeof LogsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-detail': {
      id: '/master-detail'
      path: '/master-detail'
      fullPath: '/master-detail'
      preLoaderRoute: typeof MasterDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate-v9': {
      id: '/migrate-v9'
      path: '/migrate-v9'
      fullPath: '/migrate-v9'
      preLoaderRoute: typeof MigrateV9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-cards-table': {
      id: '/mobile-cards-table'
      path: '/mobile-cards-table'
      fullPath: '/mobile-cards-table'
      preLoaderRoute: typeof MobileCardsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/params-filter-table': {
      id: '/params-filter-table'
      path: '/params-filter-table'
      fullPath: '/params-filter-table'
      preLoaderRoute: typeof ParamsFilterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pivot-table': {
      id: '/pivot-table'
      path: '/pivot-table'
      fullPath: '/pivot-table'
      preLoaderRoute: typeof PivotTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-dashboard-table': {
      id: '/production-dashboard-table'
      path: '/production-dashboard-table'
      fullPath: '/production-dashboard-table'
      preLoaderRoute: typeof ProductionDashboardTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorder-table': {
      id: '/reorder-table'
      path: '/reorder-table'
      fullPath: '/reorder-table'
      preLoaderRoute: typeof ReorderTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resizable-table': {
      id: '/resizable-table'
      path: '/resizable-table'
      fullPath: '/resizable-table'
      preLoaderRoute: typeof ResizableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-combined-table': {
      id: '/server-combined-table'
      path: '/server-combined-table'
      fullPath: '/server-combined-table'
      preLoaderRoute: typeof ServerCombinedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-filter': {
      id: '/server-filter'
      path: '/server-filter'
      fullPath: '/server-filter'
      preLoaderRoute: typeof ServerFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-table': {
      id: '/server-table'
      path: '/server-table'
      fullPath: '/server-table'
      preLoaderRoute: typeof ServerTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreadsheet-table': {
      id: '/spreadsheet-table'
      path: '/spreadsheet-table'
      fullPath: '/spreadsheet-table'
      preLoaderRoute: typeof SpreadsheetTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolbar-filter-table': {
      id: '/toolbar-filter-table'
      path: '/toolbar-filter-table'
      fullPath: '/toolbar-filter-table'
      preLoaderRoute: typeof ToolbarFilterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-reorder': {
      id: '/tree-reorder'
      path: '/tree-reorder'
      fullPath: '/tree-reorder'
      preLoaderRoute: typeof TreeReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-select': {
      id: '/tree-select'
      path: '/tree-select'
      fullPath: '/tree-select'
      preLoaderRoute: typeof TreeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-table': {
      id: '/tree-table'
      path: '/tree-table'
      fullPath: '/tree-table'
      preLoaderRoute: typeof TreeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility-table': {
      id: '/utility-table'
      path: '/utility-table'
      fullPath: '/utility-table'
      preLoaderRoute: typeof UtilityTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/': {
      id: '/v9/'
      path: '/v9'
      fullPath: '/v9/'
      preLoaderRoute: typeof V9IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/animated-icons-table': {
      id: '/v9/animated-icons-table'
      path: '/v9/animated-icons-table'
      fullPath: '/v9/animated-icons-table'
      preLoaderRoute: typeof V9AnimatedIconsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/async-actions-table': {
      id: '/v9/async-actions-table'
      path: '/v9/async-actions-table'
      fullPath: '/v9/async-actions-table'
      preLoaderRoute: typeof V9AsyncActionsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/column-pinning-table': {
      id: '/v9/column-pinning-table'
      path: '/v9/column-pinning-table'
      fullPath: '/v9/column-pinning-table'
      preLoaderRoute: typeof V9ColumnPinningTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/comparison-table': {
      id: '/v9/comparison-table'
      path: '/v9/comparison-table'
      fullPath: '/v9/comparison-table'
      preLoaderRoute: typeof V9ComparisonTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/conditional-formatting-table': {
      id: '/v9/conditional-formatting-table'
      path: '/v9/conditional-formatting-table'
      fullPath: '/v9/conditional-formatting-table'
      preLoaderRoute: typeof V9ConditionalFormattingTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/data-table': {
      id: '/v9/data-table'
      path: '/v9/data-table'
      fullPath: '/v9/data-table'
      preLoaderRoute: typeof V9DataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/deployments-table': {
      id: '/v9/deployments-table'
      path: '/v9/deployments-table'
      fullPath: '/v9/deployments-table'
      preLoaderRoute: typeof V9DeploymentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/editable-table': {
      id: '/v9/editable-table'
      path: '/v9/editable-table'
      fullPath: '/v9/editable-table'
      preLoaderRoute: typeof V9EditableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/export-config-table': {
      id: '/v9/export-config-table'
      path: '/v9/export-config-table'
      fullPath: '/v9/export-config-table'
      preLoaderRoute: typeof V9ExportConfigTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/export-selected-table': {
      id: '/v9/export-selected-table'
      path: '/v9/export-selected-table'
      fullPath: '/v9/export-selected-table'
      preLoaderRoute: typeof V9ExportSelectedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/filter-state-shape-table': {
      id: '/v9/filter-state-shape-table'
      path: '/v9/filter-state-shape-table'
      fullPath: '/v9/filter-state-shape-table'
      preLoaderRoute: typeof V9FilterStateShapeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/filter-toolbar-table': {
      id: '/v9/filter-toolbar-table'
      path: '/v9/filter-toolbar-table'
      fullPath: '/v9/filter-toolbar-table'
      preLoaderRoute: typeof V9FilterToolbarTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/grouped-table': {
      id: '/v9/grouped-table'
      path: '/v9/grouped-table'
      fullPath: '/v9/grouped-table'
      preLoaderRoute: typeof V9GroupedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/heatmap-table': {
      id: '/v9/heatmap-table'
      path: '/v9/heatmap-table'
      fullPath: '/v9/heatmap-table'
      preLoaderRoute: typeof V9HeatmapTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/infinite-scroll-table': {
      id: '/v9/infinite-scroll-table'
      path: '/v9/infinite-scroll-table'
      fullPath: '/v9/infinite-scroll-table'
      preLoaderRoute: typeof V9InfiniteScrollTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/inventory-allocation-table': {
      id: '/v9/inventory-allocation-table'
      path: '/v9/inventory-allocation-table'
      fullPath: '/v9/inventory-allocation-table'
      preLoaderRoute: typeof V9InventoryAllocationTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/kpi-table': {
      id: '/v9/kpi-table'
      path: '/v9/kpi-table'
      fullPath: '/v9/kpi-table'
      preLoaderRoute: typeof V9KpiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/live-status-table': {
      id: '/v9/live-status-table'
      path: '/v9/live-status-table'
      fullPath: '/v9/live-status-table'
      preLoaderRoute: typeof V9LiveStatusTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/logs-table': {
      id: '/v9/logs-table'
      path: '/v9/logs-table'
      fullPath: '/v9/logs-table'
      preLoaderRoute: typeof V9LogsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/master-detail': {
      id: '/v9/master-detail'
      path: '/v9/master-detail'
      fullPath: '/v9/master-detail'
      preLoaderRoute: typeof V9MasterDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/mobile-cards-table': {
      id: '/v9/mobile-cards-table'
      path: '/v9/mobile-cards-table'
      fullPath: '/v9/mobile-cards-table'
      preLoaderRoute: typeof V9MobileCardsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/params-filter-table': {
      id: '/v9/params-filter-table'
      path: '/v9/params-filter-table'
      fullPath: '/v9/params-filter-table'
      preLoaderRoute: typeof V9ParamsFilterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/pivot-table': {
      id: '/v9/pivot-table'
      path: '/v9/pivot-table'
      fullPath: '/v9/pivot-table'
      preLoaderRoute: typeof V9PivotTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/production-dashboard-table': {
      id: '/v9/production-dashboard-table'
      path: '/v9/production-dashboard-table'
      fullPath: '/v9/production-dashboard-table'
      preLoaderRoute: typeof V9ProductionDashboardTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/reorder-table': {
      id: '/v9/reorder-table'
      path: '/v9/reorder-table'
      fullPath: '/v9/reorder-table'
      preLoaderRoute: typeof V9ReorderTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/resizable-table': {
      id: '/v9/resizable-table'
      path: '/v9/resizable-table'
      fullPath: '/v9/resizable-table'
      preLoaderRoute: typeof V9ResizableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/server-combined-table': {
      id: '/v9/server-combined-table'
      path: '/v9/server-combined-table'
      fullPath: '/v9/server-combined-table'
      preLoaderRoute: typeof V9ServerCombinedTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/server-filter': {
      id: '/v9/server-filter'
      path: '/v9/server-filter'
      fullPath: '/v9/server-filter'
      preLoaderRoute: typeof V9ServerFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/server-table': {
      id: '/v9/server-table'
      path: '/v9/server-table'
      fullPath: '/v9/server-table'
      preLoaderRoute: typeof V9ServerTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/spreadsheet-table': {
      id: '/v9/spreadsheet-table'
      path: '/v9/spreadsheet-table'
      fullPath: '/v9/spreadsheet-table'
      preLoaderRoute: typeof V9SpreadsheetTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/toolbar-filter-table': {
      id: '/v9/toolbar-filter-table'
      path: '/v9/toolbar-filter-table'
      fullPath: '/v9/toolbar-filter-table'
      preLoaderRoute: typeof V9ToolbarFilterTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/tree-reorder': {
      id: '/v9/tree-reorder'
      path: '/v9/tree-reorder'
      fullPath: '/v9/tree-reorder'
      preLoaderRoute: typeof V9TreeReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/tree-select': {
      id: '/v9/tree-select'
      path: '/v9/tree-select'
      fullPath: '/v9/tree-select'
      preLoaderRoute: typeof V9TreeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/tree-table': {
      id: '/v9/tree-table'
      path: '/v9/tree-table'
      fullPath: '/v9/tree-table'
      preLoaderRoute: typeof V9TreeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9/utility-table': {
      id: '/v9/utility-table'
      path: '/v9/utility-table'
      fullPath: '/v9/utility-table'
      preLoaderRoute: typeof V9UtilityTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimatedIconsTableRoute: AnimatedIconsTableRoute,
  AsyncActionsTableRoute: AsyncActionsTableRoute,
  ColumnPinningTableRoute: ColumnPinningTableRoute,
  ComparisonTableRoute: ComparisonTableRoute,
  ConditionalFormattingTableRoute: ConditionalFormattingTableRoute,
  DataTableRoute: DataTableRoute,
  DeploymentsTableRoute: DeploymentsTableRoute,
  EditableTableRoute: EditableTableRoute,
  ExportConfigTableRoute: ExportConfigTableRoute,
  ExportSelectedTableRoute: ExportSelectedTableRoute,
  FilterStateShapeTableRoute: FilterStateShapeTableRoute,
  FilterToolbarTableRoute: FilterToolbarTableRoute,
  GroupedTableRoute: GroupedTableRoute,
  HeatmapTableRoute: HeatmapTableRoute,
  InfiniteScrollTableRoute: InfiniteScrollTableRoute,
  InventoryAllocationTableRoute: InventoryAllocationTableRoute,
  KpiTableRoute: KpiTableRoute,
  LiveStatusTableRoute: LiveStatusTableRoute,
  LogsTableRoute: LogsTableRoute,
  MasterDetailRoute: MasterDetailRoute,
  MigrateV9Route: MigrateV9Route,
  MobileCardsTableRoute: MobileCardsTableRoute,
  ParamsFilterTableRoute: ParamsFilterTableRoute,
  PivotTableRoute: PivotTableRoute,
  ProductionDashboardTableRoute: ProductionDashboardTableRoute,
  ReorderTableRoute: ReorderTableRoute,
  ResizableTableRoute: ResizableTableRoute,
  ServerCombinedTableRoute: ServerCombinedTableRoute,
  ServerFilterRoute: ServerFilterRoute,
  ServerTableRoute: ServerTableRoute,
  SpreadsheetTableRoute: SpreadsheetTableRoute,
  ToolbarFilterTableRoute: ToolbarFilterTableRoute,
  TreeReorderRoute: TreeReorderRoute,
  TreeSelectRoute: TreeSelectRoute,
  TreeTableRoute: TreeTableRoute,
  UtilityTableRoute: UtilityTableRoute,
  V9AnimatedIconsTableRoute: V9AnimatedIconsTableRoute,
  V9AsyncActionsTableRoute: V9AsyncActionsTableRoute,
  V9ColumnPinningTableRoute: V9ColumnPinningTableRoute,
  V9ComparisonTableRoute: V9ComparisonTableRoute,
  V9ConditionalFormattingTableRoute: V9ConditionalFormattingTableRoute,
  V9DataTableRoute: V9DataTableRoute,
  V9DeploymentsTableRoute: V9DeploymentsTableRoute,
  V9EditableTableRoute: V9EditableTableRoute,
  V9ExportConfigTableRoute: V9ExportConfigTableRoute,
  V9ExportSelectedTableRoute: V9ExportSelectedTableRoute,
  V9FilterStateShapeTableRoute: V9FilterStateShapeTableRoute,
  V9FilterToolbarTableRoute: V9FilterToolbarTableRoute,
  V9GroupedTableRoute: V9GroupedTableRoute,
  V9HeatmapTableRoute: V9HeatmapTableRoute,
  V9InfiniteScrollTableRoute: V9InfiniteScrollTableRoute,
  V9InventoryAllocationTableRoute: V9InventoryAllocationTableRoute,
  V9KpiTableRoute: V9KpiTableRoute,
  V9LiveStatusTableRoute: V9LiveStatusTableRoute,
  V9LogsTableRoute: V9LogsTableRoute,
  V9MasterDetailRoute: V9MasterDetailRoute,
  V9MobileCardsTableRoute: V9MobileCardsTableRoute,
  V9ParamsFilterTableRoute: V9ParamsFilterTableRoute,
  V9PivotTableRoute: V9PivotTableRoute,
  V9ProductionDashboardTableRoute: V9ProductionDashboardTableRoute,
  V9ReorderTableRoute: V9ReorderTableRoute,
  V9ResizableTableRoute: V9ResizableTableRoute,
  V9ServerCombinedTableRoute: V9ServerCombinedTableRoute,
  V9ServerFilterRoute: V9ServerFilterRoute,
  V9ServerTableRoute: V9ServerTableRoute,
  V9SpreadsheetTableRoute: V9SpreadsheetTableRoute,
  V9ToolbarFilterTableRoute: V9ToolbarFilterTableRoute,
  V9TreeReorderRoute: V9TreeReorderRoute,
  V9TreeSelectRoute: V9TreeSelectRoute,
  V9TreeTableRoute: V9TreeTableRoute,
  V9UtilityTableRoute: V9UtilityTableRoute,
  V9IndexRoute: V9IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
